SET( CPP_COMMON_TOOLS_DIR ${CMAKE_CURRENT_LIST_DIR} )

OPTION(SHOW_LOG "show log" ON )
IF(SHOW_LOG)
    ADD_DEFINITIONS(-DSHOW_LOG)
    IF(CMAKE_SYSTEM_NAME MATCHES "^Android")
        LIST( APPEND 3RD_LIBS log )
    ENDIF()
ENDIF(SHOW_LOG)
INCLUDE_DIRECTORIES( ${CMAKE_CURRENT_LIST_DIR}/include )
INCLUDE( ${CMAKE_CURRENT_LIST_DIR}/script/submodule_function.cmake )

IF(CMAKE_SYSTEM_NAME MATCHES "^Windows")
    ADD_DEFINITIONS( -DNOMINMAX )
ENDIF()

